### ISSUE TITLE
I can I can select text inline editing and turn it into a link (or edit/remove existing link)

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#35]

**Comment by djay** [comment]
This is one could be a little tricky because ideally you would want the link input to be done by the admin UI so as to keep the UI code as simple as possible in hydra.js so it's less likely to interfer with the frontend js/css.

Quanta specifies it should appear overtop of where the quanta bar was however.

![Image](https://github.com/collective/volto-hydra/assets/41700/11200609-a999-4151-a5ad-7abac123d178)

As discussed in the meeting probably the way it will work is 
- url input is done by hydrajs on the frontend. It's should be a simple input. 
- if the picker is clicked then it will send a command to the adminUI to show the picker in the sidebar
- when go/save is clicked that will instruct the adminUI to create a new node and then that will result in the editable being updated

**Comment by djay** [comment]
Just noticed quanta doesn't make it clear how to remove a link. Clicking link button would have to edit an existing link not remove it. 
Maybe you are supposed to remove the text of the link and confirm?

Seperate issue but 
The confirm arrow in volto and quanta I don't like. It's easy to forgot to click it and then your changes aren't saved.

**Comment by djay** [comment]
@MAX-786 I can't get it to work.

- [ ] Entering a url has an exception. ```TypeError: Cannot read properties of null (reading 'outerHTML') at HTMLButtonElement.<anonymous> (hydra.js:506:58)```
- [ ] arrow needs to be white
- [ ] It should appear to replace the quanta toolbar. So overtop of it
   - ![Image](https://github.com/user-attachments/assets/1c7857a9-c72f-4c65-ba39-0f4ae20f80d3)
- [ ] the browse button doesn't work

**Comment by MAX-786** [comment]
>  Entering a url has an exception. TypeError: Cannot read properties of null (reading 'outerHTML') at HTMLButtonElement.<anonymous> (hydra.js:506:58)

I wasn't able to reproduce this error, can you provide any steps or anything but ig we can work on these now on later terms ...

**Comment by djay** [comment]
@MAX-786 I got it to work once. and other times I got that exception. I couldn't isolate a difference it steps but is is an example

1. click the block
2. select the word can
3. click link
4. type rule
5. click confirm - nothing happens. exception


![Image](https://github.com/user-attachments/assets/cac8c917-f793-44a3-88e9-4f054a8f9761)

Slightly different problem is that you can select a new block and a word at the same time by double clicking a word but that then loses the word selection so formatting it doesn't work.
